config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  #belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to :action => 'new', notice: 'Product was successfully created.' }
        format.json { render json: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :company, :description, :quantity, :buy_price, :sell_price, :location)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @products = Product.all
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    customer_name = transaction_post["customer_name"]
    phone = transaction_post["phone"]

    transaction_post["list"].each do |k,item|
      total_amount = item["price"].to_f * item["quantity"].to_i
      Transaction.create(customer_name: customer_name, mobile_number: phone, description: item["description"], product: item["product"], price: item["price"], quantity: item["quantity"], total_amount: total_amount)
    end
    redirect_to action: "index"
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:customer_name, :mobile_number, :product, :price, :quantity, :total_amount)
    end

    def transaction_post
      params.require(:transactions)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Yogesh Electricals", products_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Make a Bill', new_transaction_path %></li>
          <li><%= link_to 'Transaction History', transactions_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :buy_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :buy_price, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sell_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :sell_price, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @product, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing product</h1>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <%= link_to new_product_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Product
  <% end %>
  <h1>Listing products</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover" id="products">
    <thead>
      <tr>
            <th>Name</th>
            <th>Company</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Buy price</th>
            <th>Sell price</th>
            <th>Location</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @products) do |product| %>
            <td><%= product.name %></td>
            <td><%= product.company %></td>
            <td><%= product.description %></td>
            <td><%= product.quantity %></td>
            <td><%= product.buy_price %></td>
            <td><%= product.sell_price %></td>
            <td><%= product.location %></td>
            <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#products').DataTable( {
        "order": [[ 3, "desc" ]]
    } );
} );
</script>

app/views/products/new.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Go to Product List
  <% end %>
  <h1>New product</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_product_path(@product), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show product</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @product.name %></dd>

  <dt>Company:</dt>
  <dd><%= @product.company %></dd>

  <dt>Description:</dt>
  <dd><%= @product.description %></dd>

  <dt>Quantity:</dt>
  <dd><%= @product.quantity %></dd>

  <dt>Buy price:</dt>
  <dd><%= @product.buy_price %></dd>

  <dt>Sell price:</dt>
  <dd><%= @product.sell_price %></dd>

  <dt>Location:</dt>
  <dd><%= @product.location %></dd>

</dl>

app/views/transactions/_form.html.erb
<%= form_for(@transaction, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @transaction.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h4>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :customer_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :customer_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mobile_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :mobile_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :product, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :product, class: "form-control" %>
    </div>

<div class="ui-widget">
  <label for="tags">Tags: </label>
  <input id="tags">
</div>

  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_amount, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :total_amount, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $( function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
</script>

app/views/transactions/_invoice.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h2>Invoice</h2><h3 class="pull-right">Order # 12345</h3>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    				<strong>Billed To:</strong><br>
    					John Smith<br>
    					1234 Main<br>
    					Apt. 4B<br>
    					Springfield, ST 54321
    				</address>
    			</div>
    		</div>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    					<strong>Payment Method:</strong><br>
    					Visa ending **** 4242<br>
    					jsmith@email.com
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Order Date:</strong><br>
    					March 7, 2014<br><br>
    				</address>
    			</div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Order summary</strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table class="table table-condensed">
    						<thead>
                                <tr>
        							<td><strong>Item</strong></td>
        							<td class="text-center"><strong>Price</strong></td>
        							<td class="text-center"><strong>Quantity</strong></td>
        							<td class="text-right"><strong>Totals</strong></td>
                                </tr>
    						</thead>
    						<tbody>
    							<!-- foreach ($order->lineItems as $line) or some such thing here -->
    							<tr>
    								<td>BS-200</td>
    								<td class="text-center">$10.99</td>
    								<td class="text-center">1</td>
    								<td class="text-right">$10.99</td>
    							</tr>
                                <tr>
      							<td>BS-400</td>
    								<td class="text-center">$20.00</td>
    								<td class="text-center">3</td>
    								<td class="text-right">$60.00</td>
    							</tr>
                                <tr>
            						<td>BS-1000</td>
    								<td class="text-center">$600.00</td>
    								<td class="text-center">1</td>
    								<td class="text-right">$600.00</td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Total</strong></td>
    								<td class="no-line text-right">$685.99</td>
    							</tr>
    						</tbody>
    					</table>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

app/views/transactions/edit.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @transaction, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing transaction</h1>
</div>

<%= render 'form' %>

app/views/transactions/index.html.erb
<div class="page-header">
  <%= link_to new_transaction_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Make a New Bill
  <% end %>
  <h1>Listing transactions</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover" id="transactions">
    <thead>
      <tr>
        <th>Customer name</th>
        <th>Mobile number</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total amount</th>
        <!-- <th></th>
        <th></th>
        <th></th> -->
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @transactions) do |transaction| %>
            <td><%= transaction.customer_name %></td>
            <td><%= transaction.mobile_number %></td>
            <td><%= transaction.product %></td>
            <td><%= transaction.price %></td>
            <td><%= transaction.quantity %></td>
            <td><%= transaction.total_amount %></td>
            <!-- <td><%#= link_to 'Show', transaction %></td>
            <td><%#= link_to 'Edit', edit_transaction_path(transaction) %></td>
            <td><%#= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#transactions').DataTable( {
        "order": [[ 3, "desc" ]]
    } );
} );
</script>

app/views/transactions/new.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Bill</h1>
</div>

<%= form_for(@transaction, html: { role: "form" }) do |f| %>
<div class="container">
    <div class="row">
    	<div class="col-xs-12">
    		<div class="col-xs-6">
       		<label class="control-label" for="transactions[customer_name]">Customer Name :</label>
       		<input type="text" class="form-control" name="transactions[customer_name]" required/>
       </div>
       <div class="col-xs-6">
       		<label class="control-label" for="transactions[phone]">Mobile Number :</label>
       		<input type="text" class="form-control" name="transactions[phone]" pattern="^[6-9]\d{9}$" required/>
       </div>       
      </div>
    </div>
</div>
<hr>
<div>
	<a href="" class="btn btn-primary" id="add_product">Add Product</a>
</div>
<table class="table table-striped table-hover" id="bill_products">
  <thead>
    <tr>
      <th>Product</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total amount</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  	<tr>
  		<td><input type="text" name="transactions[list][0][product]" class="product" list="products" required/></td>
  		<td><input type="text" name="transactions[list][0][description]" class="description" required/></td>
	    <td><input class="price" name="transactions[list][0][price]" type="number" required/></td>
	    <td><input class="quantity" name="transactions[list][0][quantity]" value="1" min="1" type="number" required/></td>
	    <td><input class="sub_total" name="sub_total"/></td>
	    <td><a class="glyphicon glyphicon-remove remove_product"></a></td>
  	</tr>
  </tbody>
  <tfoot>
    <tr>
    <td></td>
    <td></td>
    <td></td>
    <td><strong>Total Bill:</strong></td>
    <td><input type="text" class="grand_total" value="" name="" disabled/></td>
    <td></td>
    </tr>
</tfoot>
</table>
<datalist id="products">
	<% @products.each do |product| %>
  <option data-desc="<%= product.description%>" data-sellprice="<%= product.sell_price%>" value="<%= product.name%>"><%= product.name %></option>
  <% end %>
</datalist>

<div class="form-group">
    <div class="col-sm-10">
      <%= f.submit "Create Bill", {class: "btn btn-primary"} %>
    </div>
  </div>
<% end %>



<script type="text/javascript">
	function fixIds(elem, cntr) {
		cntr++;	
    $(elem).find("input").each(function() {
    	this.name = this.name.replace(/\d+/,cntr);
    })
	}
	$( "#add_product" ).click(function() {
		var row = $("#bill_products tbody tr:last").clone(true).find('input').val('').end();
		var initialCounter = $("#bill_products tbody tr:last").find('input').attr("name").match(/\d+/)[0];
		var cloneCntr = parseInt(initialCounter);
		fixIds(row, cloneCntr);
    $(row).find('.quantity').prop('value',1);
		row.insertAfter("#bill_products tbody tr:last");
    return false;
	});

	// $( "#add_product" ).click(function() {
	// 	$("#bill_products tbody tr:last").clone(true).find('input').val('').end().insertAfter("#bill_products tbody tr:last");
 //    return false;
	// });

	$(".product").on('input', function () {
    var value = $(this).val();
    var price = $('#products [value="' + value + '"]').data('sellprice');
    var description = $('#products [value="' + value + '"]').data('desc');
    $(this).closest('tr').find("[class=price]").val(price);
    $(this).closest('tr').find("[class=description]").val(description);
	});
</script>

app/views/transactions/show.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_transaction_path(@transaction), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show transaction</h1>
</div>

<dl class="dl-horizontal">
  <dt>Customer name:</dt>
  <dd><%= @transaction.customer_name %></dd>

  <dt>Mobile number:</dt>
  <dd><%= @transaction.mobile_number %></dd>

  <dt>Product:</dt>
  <dd><%= @transaction.product %></dd>

  <dt>Price:</dt>
  <dd><%= @transaction.price %></dd>

  <dt>Quantity:</dt>
  <dd><%= @transaction.quantity %></dd>

  <dt>Total amount:</dt>
  <dd><%= @transaction.total_amount %></dd>

</dl>